### ISSUE TITLE
Does it support "centrifugo V5"?

### ISSUE THREAD

**Issue by fredsal** [Opekunov/laravel-centrifugo-broadcaster#21]
[https://github.com/centrifugal/centrifugo/releases/v5.2.2](https://github.com/centrifugal/centrifugo/releases/tag/v5.2.2)

Does it work only with v4, or is v5 also supported?

**Comment by Opekunov** [comment]
When the 5th version was released, I asked the developer. He said that the old API was still working, but I couldn't verify it.

**Comment by fredsal** [comment]
Ok, thanks for answer, seems like it supports old format, but old format is deprecated
https://centrifugal.dev/docs/getting-started/migration_v5

**Comment by Opekunov** [comment]
closed [3.0.1](https://github.com/Opekunov/laravel-centrifugo-broadcaster/releases/tag/v3.0.1)
